### ISSUE TITLE
Replace RegWrite/RegRead commands in OEM Function due to AVs (BD, Microsoft Defender, Norton360 etc..) are flagging script for this.

### ISSUE THREAD

**Issue by Jivaross** [Jivaross/W10-Configurator#9]

**Comment by mlipok** [comment]
Which AV ?

**Comment by Jivaross** [comment]
BitDefender and Norton 360 does flag automatically compiled scripts by default, I don't really remember what was the flag yet I'll dig into it

**Comment by Jivaross** [comment]
Problem found, apparently AVs doesn't like Autoit command RegWrite/RegRead, so this will need to be replaced to something else..

**Comment by LordStewie** [comment]
While looking into this I believe that the AV software companies as defined [within this list](https://www.virustotal.com/gui/file/9730d394e5164741cac3af100bf8577420210105374767254488ad0336b1b86c/detection) will flag the application even if it is just the GUI and no functions added in to the code. May need to submit the application to the vendors that are flagging the application so that they can adjust their scanners to show that it is not malicious code once the application is complete.

**Comment by Jivaross** [comment]
from the result I see, only mcafee is a "problem", I dont really care if its flagged by unknown AV personally and for mcafee its GW edition only

**Comment by Jivaross** [comment]
### ISSUE CLOSED
I will provide the project exe to popular AVs before project release.
